### ISSUE TITLE
Button text not rendering

### ISSUE THREAD

**Issue by skreborn** [thscharler/rat-widget#1]
Button text does not render anymore because the layout the widget [calculates](https://github.com/thscharler/rat-widget/blob/master/src/button.rs#L244-L246) ends up having a height of zero.

This happens because [`mem::take`](https://doc.rust-lang.org/std/mem/fn.take.html) is [used](https://github.com/thscharler/rat-widget/blob/master/src/button.rs#L198) when rendering the `StatefulWidget`, which replaces the original `text` with one that contains zero lines.

**Comment by thscharler** [comment]
Oh, you have been using anything of this?

But yes, I noticed this, and a few other places where my last refactor around StatefulWidgetRef broke something. 

I'm sure I commited the fix, but haven't published an updated crate yet. 

--

And really, I've considered all of this alpha until now, but I have plans to go beta at the end of september. ... Maybe I should've stated this somewhere :-o

**Comment by skreborn** [comment]
It's quite alright, I knew going in that it was a relatively fresh project. Even so, it's serving us well in a simple application.

**Comment by thscharler** [comment]
Well, I'm in the middle of something, but I can put out a new release this week I think. And I will be a bit more careful now that I know somebody is actually using it :-)

**Comment by thscharler** [comment]
Which of the widgets are you using btw?

**Comment by skreborn** [comment]
> Which of the widgets are you using btw?

Button and table most of all, not much else at the moment.

**Comment by thscharler** [comment]
Nice!

ping me anytime you run into issues with the public api. 
making that nice and smooth is my main concern currently.

**Comment by thscharler** [comment]
I published the changed crates now.
